//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_LGVEntities : DbContext
    {
        public DB_LGVEntities()
            : base("name=DB_LGVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Category> TB_Category { get; set; }
        public virtual DbSet<TB_Supp> TB_Supp { get; set; }
        public virtual DbSet<TB_Purchases> TB_Purchases { get; set; }
        public virtual DbSet<TB_Clients> TB_Clients { get; set; }
        public virtual DbSet<TB_Sales> TB_Sales { get; set; }
        public virtual DbSet<TB_Users> TB_Users { get; set; }
    }
}
