//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGV
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Clients
    {
        public int ID { get; set; }
        public string Supp_Name { get; set; }
        public string Supp_Phone { get; set; }
        public string Supp_Email { get; set; }
        public byte[] Supp_Image { get; set; }
    }
}
