//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGV
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Sales
    {
        public int ID { get; set; }
        public string Sale_Name { get; set; }
        public string Sale_Client { get; set; }
        public Nullable<double> Sale_Price { get; set; }
        public Nullable<double> Sale_Qt { get; set; }
        public Nullable<double> Sale_Tprice { get; set; }
        public Nullable<System.DateTime> Sale_Date { get; set; }
    }
}
