using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using LGV.EIL;

namespace LGV.Interface_Layer
{
    public partial class Category_Form : Form
    {
        DB_LGVEntities db = new DB_LGVEntities();
        TB_Category tb_category = new TB_Category();
        Business_Layer.Methods methods = new Business_Layer.Methods();
        int id;

        public Category_Form()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            LGV.DB_LGVEntities dbContext = new LGV.DB_LGVEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Category.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_Category.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            Interface_Layer.Category_Add_Form add_form = new Interface_Layer.Category_Add_Form();
            add_form.id = 0;
            add_form.btn_add.Text = "Ajouter";
            add_form.Show();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Dialogue dialogue = new Dialogue();

            try
            {
                id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));
                var result = MessageBox.Show("Opération du supprimer", "Etes-vous sûr de cette opération", MessageBoxButtons.YesNo);

                if (result == DialogResult.Yes)
                {
                    tb_category = db.TB_Category.Where(x => x.ID == id).FirstOrDefault();
                    db.Entry(tb_category).State = EntityState.Deleted;
                    db.SaveChanges();
                    update_data();
                }
            }
            catch
            {
                dialogue.txt_caption.Text = "Il n'y a aucune catégorie à supprimer";
                dialogue.Width = this.Width;
                dialogue.Show();
            }
            
        }

        private void update_data()
        {
            db = new DB_LGVEntities();
            gridControl1.DataSource = db.TB_Category.ToList();
        }

        private void btn_update_Click(object sender, EventArgs e)
        {
            update_data();

        }

        // Modifier
        private void btn_edit_Click(object sender, EventArgs e)
        {
            Interface_Layer.Category_Add_Form add_form = new Interface_Layer.Category_Add_Form();
            id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));
            tb_category = db.TB_Category.Where(x => x.ID == id).FirstOrDefault();
            add_form.edit_name.Text = tb_category.Category_Name.ToString();
            methods.by = tb_category.Category_Cover;
            add_form.pic_cover.Image = Image.FromStream(methods.convert_image());
            
            add_form.id = id;
            add_form.btn_add.Text = "Modifier";
            add_form.Show(); 
        }

        private void btn_search_Click(object sender, EventArgs e)
        {
            var _search = edit_search.Text;
            gridControl1.DataSource = db.TB_Category.Where(x => x.Category_Name.Contains(_search)).ToList();
        }
    }
}
